version: '2.4'

x-elasticsearch-node: &elasticsearch-node
  image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
  ulimits:
    memlock:
      soft: -1
      hard: -1
  networks:
    - esnet

services:
  es-node-1:
    container_name: es-node-1
    <<: *elasticsearch-node
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=es-node-1,es-node-2
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=es-node-1
      - discovery.seed_hosts=es-node-2
    ports:
      - "9200:9200"
  es-node-2:
    container_name: es-node-2
    <<: *elasticsearch-node
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=es-node-1,es-node-2
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=es-node-2
      - discovery.seed_hosts=es-node-1

volumes:
  esdata1:
    driver: local
    driver_opts:
      type: none
      device: /data/elasticsearch/nodes/node1
      o: bind
  esdata2:
    driver: local
    driver_opts:
      type: none
      device: /data/elasticsearch/nodes/node2
      o: bind

networks:
  esnet:

